# Generated by Django 5.2.6 on 2025-09-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embassy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
